version: "3.8"

services:
  icar:
    build: .
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=42
      - DISPLAY=${DISPLAY:-}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
    stdin_open: true
    tty: true
